### ISSUE TITLE
Some more findings when testing windows.

### ISSUE THREAD

**Issue by iandesj** [akroma-project/akroma-wallet-desktop#41] opened 2018-06-23 18:34 UTC
- [x] Deleting a wallet doesn't clear it from some configuration as when I re-import that UTC file back into the keystore and re-open the wallet, I can't rename the wallet.  You just keep getting this error: ```polyfills.c0ec508….bundle.js:1 ERROR Error: Uncaught (in promise): {"status":409,"name":"conflict","message":"Document update conflict"}
    at P (polyfills.c0ec508….bundle.js:1)
    at polyfills.c0ec508….bundle.js:1
    at s (main.36367fa….bundle.js:1)
    at e.invoke (polyfills.c0ec508….bundle.js:1)
    at Object.onInvoke (main.36367fa….bundle.js:1)
    at e.invoke (polyfills.c0ec508….bundle.js:1)
    at t.run (polyfills.c0ec508….bundle.js:1)
    at polyfills.c0ec508….bundle.js:1
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)```

- [x] Clicking copy address copies the address, but leaves the pop-out open.  You have to click away from it for it to go away
- [x] The scannable code isn't clickable.  Is it just a placeholder for the moment?
- [ ] On the main screen, Send and Receive do nothing.  Either remove the buttons, or have them go to a standard send/receive page
- [ ] Again, feature request, but some sortable method for your wallets.  Maybe by name ASC/DESC, balance ASC/DESC
- [ ] More a feature request, but could we get it to show not just the aggregate at the top of the page, but maybe somewhere on the wallet listing, show the balance of that wallet?
- [x] Clicking on a wallet will start the sync, but instead, you just see this error:
``` ERROR Error: Uncaught (in promise): Error: Returned error: invalid argument 0: hex string without 0x prefix
Error: Returned error: invalid argument 0: hex string without 0x prefix
    at Object.ErrorResponse (main.36367fa….bundle.js:1)
    at main.36367fa….bundle.js:1
    at XMLHttpRequest.i.onreadystatechange [as zone_symbolON_PROPERTYreadystatechange] (main.36367fa….bundle.js:1)
    at XMLHttpRequest.I (polyfills.c0ec508….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at t.runTask (polyfills.c0ec508….bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.c0ec508….bundle.js:1)
    at m (polyfills.c0ec508….bundle.js:1)
    at Object.ErrorResponse (main.36367fa….bundle.js:1)
    at main.36367fa….bundle.js:1
    at XMLHttpRequest.i.onreadystatechange [as zone_symbolON_PROPERTYreadystatechange] (main.36367fa….bundle.js:1)
    at XMLHttpRequest.I (polyfills.c0ec508….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at t.runTask (polyfills.c0ec508….bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.c0ec508….bundle.js:1)
    at m (polyfills.c0ec508….bundle.js:1)
    at P (polyfills.c0ec508….bundle.js:1)
    at polyfills.c0ec508….bundle.js:1
    at s (main.36367fa….bundle.js:1)
    at e.invoke (polyfills.c0ec508….bundle.js:1)
    at Object.onInvoke (main.36367fa….bundle.js:1)
    at e.invoke (polyfills.c0ec508….bundle.js:1)
    at t.run (polyfills.c0ec508….bundle.js:1)
    at polyfills.c0ec508….bundle.js:1
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)
```
No indication it's syncing looking at the logs, but you do see the image.  So, not sure if it were to get past that error it'd show some percentage of completion or what

- [ ] When syncing the wallet for the first time, it shows a % and the number of blocks synced vs. total blocks to sync. However, this appears to be a snapshot in time as once you reach 100%, you technically aren't at 100% as you can see in the footer the blocks still continue to sync and until it's truly at 100%, the wallet isn't accessible. Make the max block periodically update to truly reflect how far out your are in your sync, and have the % update accordingly too.

- [ ] Somehow you should carry over the optional name of the wallet to the individual wallet screen (feature request)
- [ ] Feature request.  Before sending, you should do a popup confirmation of the data provided
- [ ] What's the point of the Receive button? :stuck_out_tongue:
- [ ] Migration guide between versions with breaking changes

**Comment by seanjnkns** [comment] 2018-06-23 18:49
Working from a clean slate, when starting, you'll get the following errors and it takes some 5+ minutes to start syncing:


polyfills.c0ec508….bundle.js:1 POST http://localhost:8545/ net::ERR_CONNECTION_REFUSED
g @ polyfills.c0ec508….bundle.js:1
e.scheduleTask @ polyfills.c0ec508….bundle.js:1
onScheduleTask @ polyfills.c0ec508….bundle.js:1
e.scheduleTask @ polyfills.c0ec508….bundle.js:1
t.scheduleTask @ polyfills.c0ec508….bundle.js:1
t.scheduleMacroTask @ polyfills.c0ec508….bundle.js:1
y @ polyfills.c0ec508….bundle.js:1
(anonymous) @ polyfills.c0ec508….bundle.js:1
M.o.(anonymous function) @ polyfills.c0ec508….bundle.js:1
o.send @ main.36367fa….bundle.js:1
u.send @ main.36367fa….bundle.js:1
h @ main.36367fa….bundle.js:1
n @ main.36367fa….bundle.js:1
(anonymous) @ main.36367fa….bundle.js:1
e.invokeTask @ polyfills.c0ec508….bundle.js:1
onInvokeTask @ main.36367fa….bundle.js:1
e.invokeTask @ polyfills.c0ec508….bundle.js:1
t.runTask @ polyfills.c0ec508….bundle.js:1
t.invokeTask @ polyfills.c0ec508….bundle.js:1
invoke @ polyfills.c0ec508….bundle.js:1
n.args.(anonymous function) @ polyfills.c0ec508….bundle.js:1
polyfills.c0ec508….bundle.js:1 ERROR Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (main.36367fa….bundle.js:1)
    at XMLHttpRequest.i.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (main.36367fa….bundle.js:1)
    at XMLHttpRequest.I (polyfills.c0ec508….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at t.runTask (polyfills.c0ec508….bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.c0ec508….bundle.js:1)
    at m (polyfills.c0ec508….bundle.js:1)
    at XMLHttpRequest._ (polyfills.c0ec508….bundle.js:1)
console.(anonymous function) @ polyfills.c0ec508….bundle.js:1
ut @ main.36367fa….bundle.js:1
WT6e.t.handleError @ main.36367fa….bundle.js:1
next @ main.36367fa….bundle.js:1
e.object.i @ main.36367fa….bundle.js:1
OVmG.e.__tryOrUnsub @ main.36367fa….bundle.js:1
OVmG.e.next @ main.36367fa….bundle.js:1
OVmG.e._next @ main.36367fa….bundle.js:1
OVmG.e.next @ main.36367fa….bundle.js:1
e.next @ main.36367fa….bundle.js:1
WT6e.e.emit @ main.36367fa….bundle.js:1
(anonymous) @ main.36367fa….bundle.js:1
e.invoke @ polyfills.c0ec508….bundle.js:1
t.run @ polyfills.c0ec508….bundle.js:1
WT6e.t.runOutsideAngular @ main.36367fa….bundle.js:1
onHandleError @ main.36367fa….bundle.js:1
e.handleError @ polyfills.c0ec508….bundle.js:1
t.runTask @ polyfills.c0ec508….bundle.js:1
t.invokeTask @ polyfills.c0ec508….bundle.js:1
invoke @ polyfills.c0ec508….bundle.js:1
n.args.(anonymous function) @ polyfills.c0ec508….bundle.js:1
polyfills.c0ec508….bundle.js:1 POST http://localhost:8545/ net::ERR_CONNECTION_REFUSED
g @ polyfills.c0ec508….bundle.js:1
e.scheduleTask @ polyfills.c0ec508….bundle.js:1
onScheduleTask @ polyfills.c0ec508….bundle.js:1
e.scheduleTask @ polyfills.c0ec508….bundle.js:1
t.scheduleTask @ polyfills.c0ec508….bundle.js:1
t.scheduleMacroTask @ polyfills.c0ec508….bundle.js:1
y @ polyfills.c0ec508….bundle.js:1
(anonymous) @ polyfills.c0ec508….bundle.js:1
M.o.(anonymous function) @ polyfills.c0ec508….bundle.js:1
o.send @ main.36367fa….bundle.js:1
u.send @ main.36367fa….bundle.js:1
h @ main.36367fa….bundle.js:1
n @ main.36367fa….bundle.js:1
(anonymous) @ main.36367fa….bundle.js:1
e.invokeTask @ polyfills.c0ec508….bundle.js:1
onInvokeTask @ main.36367fa….bundle.js:1
e.invokeTask @ polyfills.c0ec508….bundle.js:1
t.runTask @ polyfills.c0ec508….bundle.js:1
t.invokeTask @ polyfills.c0ec508….bundle.js:1
invoke @ polyfills.c0ec508….bundle.js:1
n.args.(anonymous function) @ polyfills.c0ec508….bundle.js:1
polyfills.c0ec508….bundle.js:1 POST http://localhost:8545/ net::ERR_CONNECTION_REFUSED
g @ polyfills.c0ec508….bundle.js:1
e.scheduleTask @ polyfills.c0ec508….bundle.js:1
onScheduleTask @ polyfills.c0ec508….bundle.js:1
e.scheduleTask @ polyfills.c0ec508….bundle.js:1
t.scheduleTask @ polyfills.c0ec508….bundle.js:1
t.scheduleMacroTask @ polyfills.c0ec508….bundle.js:1
y @ polyfills.c0ec508….bundle.js:1
(anonymous) @ polyfills.c0ec508….bundle.js:1
M.o.(anonymous function) @ polyfills.c0ec508….bundle.js:1
o.send @ main.36367fa….bundle.js:1
u.send @ main.36367fa….bundle.js:1
h @ main.36367fa….bundle.js:1
n @ main.36367fa….bundle.js:1
(anonymous) @ main.36367fa….bundle.js:1
e.invokeTask @ polyfills.c0ec508….bundle.js:1
onInvokeTask @ main.36367fa….bundle.js:1
e.invokeTask @ polyfills.c0ec508….bundle.js:1
t.runTask @ polyfills.c0ec508….bundle.js:1
t.invokeTask @ polyfills.c0ec508….bundle.js:1
invoke @ polyfills.c0ec508….bundle.js:1
n.args.(anonymous function) @ polyfills.c0ec508….bundle.js:1
polyfills.c0ec508….bundle.js:1 ERROR Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (main.36367fa….bundle.js:1)
    at XMLHttpRequest.i.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (main.36367fa….bundle.js:1)
    at XMLHttpRequest.I (polyfills.c0ec508….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at t.runTask (polyfills.c0ec508….bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.c0ec508….bundle.js:1)
    at m (polyfills.c0ec508….bundle.js:1)
    at XMLHttpRequest._ (polyfills.c0ec508….bundle.js:1)
console.(anonymous function) @ polyfills.c0ec508….bundle.js:1
ut @ main.36367fa….bundle.js:1
WT6e.t.handleError @ main.36367fa….bundle.js:1
next @ main.36367fa….bundle.js:1
e.object.i @ main.36367fa….bundle.js:1
OVmG.e.__tryOrUnsub @ main.36367fa….bundle.js:1
OVmG.e.next @ main.36367fa….bundle.js:1
OVmG.e._next @ main.36367fa….bundle.js:1
OVmG.e.next @ main.36367fa….bundle.js:1
e.next @ main.36367fa….bundle.js:1
WT6e.e.emit @ main.36367fa….bundle.js:1
(anonymous) @ main.36367fa….bundle.js:1
e.invoke @ polyfills.c0ec508….bundle.js:1
t.run @ polyfills.c0ec508….bundle.js:1
WT6e.t.runOutsideAngular @ main.36367fa….bundle.js:1
onHandleError @ main.36367fa….bundle.js:1
e.handleError @ polyfills.c0ec508….bundle.js:1
t.runTask @ polyfills.c0ec508….bundle.js:1
t.invokeTask @ polyfills.c0ec508….bundle.js:1
invoke @ polyfills.c0ec508….bundle.js:1
n.args.(anonymous function) @ polyfills.c0ec508….bundle.js:1
polyfills.c0ec508….bundle.js:1 ERROR Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (main.36367fa….bundle.js:1)
    at XMLHttpRequest.i.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (main.36367fa….bundle.js:1)
    at XMLHttpRequest.I (polyfills.c0ec508….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at t.runTask (polyfills.c0ec508….bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.c0ec508….bundle.js:1)
    at m (polyfills.c0ec508….bundle.js:1)
    at XMLHttpRequest._ (polyfills.c0ec508….bundle.js:1)

**Comment by seanjnkns** [comment] 2018-06-23 18:57
Working off the previous comment, after the blockchain synced, I opted to create a new wallet, then clicking on the wallet so it would start syncing txs, you get the aforementioned error of:
ERROR Error: Uncaught (in promise): Error: Returned error: invalid argument 0: hex string without 0x prefix
Error: Returned error: invalid argument 0: hex string without 0x prefix
    at Object.ErrorResponse (main.36367fa….bundle.js:1)
    at main.36367fa….bundle.js:1
    at XMLHttpRequest.i.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (main.36367fa….bundle.js:1)
    at XMLHttpRequest.I (polyfills.c0ec508….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at t.runTask (polyfills.c0ec508….bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.c0ec508….bundle.js:1)
    at m (polyfills.c0ec508….bundle.js:1)
    at Object.ErrorResponse (main.36367fa….bundle.js:1)
    at main.36367fa….bundle.js:1
    at XMLHttpRequest.i.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (main.36367fa….bundle.js:1)
    at XMLHttpRequest.I (polyfills.c0ec508….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at t.runTask (polyfills.c0ec508….bundle.js:1)
    at t.invokeTask [as invoke] (polyfills.c0ec508….bundle.js:1)
    at m (polyfills.c0ec508….bundle.js:1)
    at P (polyfills.c0ec508….bundle.js:1)
    at polyfills.c0ec508….bundle.js:1
    at s (main.36367fa….bundle.js:1)
    at e.invoke (polyfills.c0ec508….bundle.js:1)
    at Object.onInvoke (main.36367fa….bundle.js:1)
    at e.invoke (polyfills.c0ec508….bundle.js:1)
    at t.run (polyfills.c0ec508….bundle.js:1)
    at polyfills.c0ec508….bundle.js:1
    at e.invokeTask (polyfills.c0ec508….bundle.js:1)
    at Object.onInvokeTask (main.36367fa….bundle.js:1)

**Comment by seanjnkns** [comment] 2018-06-23 19:12
Issue # 12:
When syncing the wallet for the first time, it shows a % and the number of blocks synced vs. total blocks to sync.  However, this appears to be a snapshot in time as once you reach 100%, you technically aren't at 100% as you can see in the footer the blocks still continue to sync and until it's truly at 100%, the wallet isn't accessible.  Make the max block periodically update to truly reflect how far out your are in your sync, and have the % update accordingly too.

**Comment by seanjnkns** [comment] 2018-06-25 16:14
Going to do a report of Linux (Fedora 28) here too based on the latest fixes made over the weekend since this report was started:

1) Working from a clean slate, when starting, you'll get the following errors as previously reported and it takes some 5+ minutes to start syncing
2) Confirmed QR code working
3) Copy Address pop-out still stays "popped" out (not fixed)
4) Clicking on a wallet will start the sync (fixed).  However, a % would be helpful in addition to the progress bar
5) Deletion and re-importing wallet and trying to rename still doesn't work
All other suggestions for features still apply and those issues marked as "not fixed" generate the same errors as previously seen.

**Closed** 2018-07-03 01:07 UTC
Labels: bug
